version: '3'

services:
  data-api:
    image: xapixio/firebird:$FIREBIRD_VERSION
    user: root
    links:
      - postgresql
      - elastic
    ports:
      - "4001:4001"
      - "4002:4002"
    environment:
      - DATASOURCE__JDBC_URL=jdbc:postgresql://postgresql:5432/postgres?user=postgres&password=password
      - ELASTICSEARCH__ENTRYPOINT=http://elastic:9200
    command: run all
