#!/bin/bash -xe

docker-compose up -d postgresql
sleep 5

docker-compose run --rm phoenix bundle exec rake db:safe_setup
docker-compose run --rm shisa bundle exec rake db:safe_setup
docker-compose run --rm phoenix bundle exec ruby standalone/seeds.rb

docker-compose up
